import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, collection, addDoc, onSnapshot, query, orderBy, doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import "./firebase-config.js";
const config = window.HOLIDAY_PET_HELPERS_FIREBASE_CONFIG || {};
const configReady = config.apiKey && config.projectId;
let app, auth, db;
let currentMonthDate = new Date(); currentMonthDate.setDate(1);
let dragStartDate = null; let dragEndDate = null; let selectedRating = 5;
let blockedDates = []; let settings = { maxPetsPerDay: 3 };
const state = { bookings: [], reviews: [], galleryPhotos: [], adminUser: null };
const els = {};
function cache(){["calendarGrid","calendarMonthLabel","startDate","endDate","bookingForm","bookingMessage","name","email","pet","photo","notes","reviewForm","reviewName","reviewText","ratingValue","reviewList","photoGallery","blockedList","bookingList","maxPets","totalBookingsCount","blockedDatesCount","busiestDayCount","dailyCountsList","adminPanel","cloudBanner"].forEach(id=>els[id]=document.getElementById(id));}
const showBanner=(m)=>els.cloudBanner&&(els.cloudBanner.textContent=m);
const cmp=(a,b)=>new Date(a+"T00:00:00")-new Date(b+"T00:00:00");
function fmt(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const monthLabel=d=>d.toLocaleDateString(undefined,{month:"long",year:"numeric"});
function dates(start,end){const r=[];let d=new Date(start+"T00:00:00"),l=new Date(end+"T00:00:00");while(d<=l){r.push(fmt(d));d.setDate(d.getDate()+1)}return r}
function counts(){const c={};state.bookings.forEach(b=>{if(!b.start||!b.end)return;dates(b.start,b.end).forEach(ds=>c[ds]=(c[ds]||0)+1)});return c}
function bookedSet(){const s=new Set();state.bookings.forEach(b=>{if(!b.start||!b.end)return;dates(b.start,b.end).forEach(ds=>s.add(ds))});return s}
function renderSelected(){if(els.startDate&&dragStartDate)els.startDate.value=dragStartDate;if(els.endDate&&dragEndDate)els.endDate.value=dragEndDate}
function inRange(ds,a,b){return a&&b&&cmp(ds,a)>=0&&cmp(ds,b)<=0}
function buildCalendar(){if(!els.calendarGrid||!els.calendarMonthLabel)return;els.calendarGrid.innerHTML="";els.calendarMonthLabel.textContent=monthLabel(currentMonthDate);const y=currentMonthDate.getFullYear(),m=currentMonthDate.getMonth(),f=new Date(y,m,1),l=new Date(y,m+1,0),start=f.getDay(),days=l.getDate(),booked=bookedSet(),c=counts();for(let i=0;i<start;i++){const e=document.createElement("div");e.className="day empty";els.calendarGrid.appendChild(e)}for(let day=1;day<=days;day++){const ds=fmt(new Date(y,m,day));const cell=document.createElement("button");cell.type="button";cell.className="day";cell.dataset.date=ds;let status="Available";if(blockedDates.includes(ds)){cell.classList.add("blocked");status="Unavailable"}else if(booked.has(ds)){cell.classList.add("booked");status="Booked"}if(dragStartDate&&ds===dragStartDate)cell.classList.add("selected");if(dragEndDate&&ds===dragEndDate)cell.classList.add("selected");if(inRange(ds,dragStartDate,dragEndDate))cell.classList.add("in-range");const count=c[ds]||0;cell.innerHTML=`<strong>${day}</strong><small>${status}</small>${count?`<span class="count-badge">${count}</span>`:""}`;els.calendarGrid.appendChild(cell)}}
function attachCalendar(){document.getElementById("prevMonthBtn")?.addEventListener("click",()=>{currentMonthDate.setMonth(currentMonthDate.getMonth()-1);buildCalendar()});document.getElementById("nextMonthBtn")?.addEventListener("click",()=>{currentMonthDate.setMonth(currentMonthDate.getMonth()+1);buildCalendar()});els.calendarGrid?.addEventListener("click",async e=>{const day=e.target.closest(".day");if(!day||day.classList.contains("empty"))return;const ds=day.dataset.date;if(state.adminUser){const idx=blockedDates.indexOf(ds);if(idx>=0)blockedDates.splice(idx,1);else blockedDates.push(ds);blockedDates.sort();await saveSettings();renderBlocked();renderStats();buildCalendar();return}if(!dragStartDate||(dragStartDate&&dragEndDate)){dragStartDate=ds;dragEndDate=null}else{if(cmp(ds,dragStartDate)<0){dragEndDate=dragStartDate;dragStartDate=ds}else dragEndDate=ds}renderSelected();buildCalendar()});let sx=0,ex=0;els.calendarGrid?.addEventListener("touchstart",e=>{sx=e.changedTouches[0].screenX},{passive:true});els.calendarGrid?.addEventListener("touchend",e=>{ex=e.changedTouches[0].screenX;const diff=ex-sx;if(Math.abs(diff)<40)return;if(diff<0)currentMonthDate.setMonth(currentMonthDate.getMonth()+1);else currentMonthDate.setMonth(currentMonthDate.getMonth()-1);buildCalendar()},{passive:true})}
const unavailable=(s,e)=>{const b=new Set(blockedDates);return dates(s,e).some(ds=>b.has(ds))};
const atCapacity=(s,e)=>{const c=counts(),max=Number(settings.maxPetsPerDay||3);return dates(s,e).some(ds=>(c[ds]||0)>=max)};
async function submitBooking(ev){ev.preventDefault();const start=els.startDate.value,end=els.endDate.value,name=els.name.value.trim(),email=els.email.value.trim(),pet=els.pet.value.trim(),notes=els.notes.value.trim(),msg=els.bookingMessage,photoFile=els.photo?.files?.[0];if(!start||!end){msg.textContent="Please choose both dates.";return}if(end<start){msg.textContent="End date must be after start date.";return}if(unavailable(start,end)){msg.textContent="One or more selected dates are unavailable.";return}if(atCapacity(start,end)){msg.textContent="One or more selected dates are already full.";return}if(!db){msg.textContent="Cloud storage is not configured yet. Add your Firebase config first.";return}let photoDataUrl="";if(photoFile){photoDataUrl=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result||"");r.readAsDataURL(photoFile)})}await addDoc(collection(db,"bookings"),{start,end,name,email,pet,notes,photoDataUrl,createdAt:serverTimestamp()});dragStartDate=start;dragEndDate=end;renderSelected();msg.textContent="Booking saved to the cloud and opening your email app…";const sub=encodeURIComponent(`Pet Booking ${pet}`),body=encodeURIComponent(`Name: ${name}
Email: ${email}
Pet: ${pet}
Start: ${start}
End: ${end}
Notes: ${notes}`);window.location.href=`mailto:hello@holidaypethelpers.com?subject=${sub}&body=${body}`;ev.target.reset()}
function renderReviews(targetId="reviewList"){const wrap=document.getElementById(targetId);if(!wrap)return;wrap.innerHTML="";if(!state.reviews.length){wrap.innerHTML='<div class="review-card"><p>No reviews yet. Be the first to leave one.</p><div class="review-meta"><strong>Holiday Pet Helpers</strong><span class="stars">★★★★★</span></div></div>';return}state.reviews.forEach(r=>{const item=document.createElement("div");item.className="review-card";const stars="★".repeat(r.rating||5)+"☆".repeat(5-(r.rating||5));item.innerHTML=`<p>${r.text}</p><div class="review-meta"><strong>${r.name}</strong><span class="stars">${stars}</span></div>`;wrap.appendChild(item)})}
function ratingPicker(){const stars=document.querySelectorAll(".star-btn"),input=document.getElementById("ratingValue");if(!stars.length||!input)return;const paint=v=>{selectedRating=v;input.value=v;stars.forEach(btn=>btn.classList.toggle("active",Number(btn.dataset.value)<=v))};paint(selectedRating);stars.forEach(btn=>btn.addEventListener("click",()=>paint(Number(btn.dataset.value))))}
async function addReview(ev){ev.preventDefault();if(!db)return;const name=document.getElementById("reviewName").value.trim(),text=document.getElementById("reviewText").value.trim(),rating=Number(document.getElementById("ratingValue").value||5);if(!name||!text)return;await addDoc(collection(db,"reviews"),{name,text,rating,createdAt:serverTimestamp()});ev.target.reset();selectedRating=5;ratingPicker()}
function renderPhotos(){if(!els.photoGallery)return;els.photoGallery.innerHTML="";if(!state.galleryPhotos.length){els.photoGallery.innerHTML='<div class="empty-state" style="grid-column:1/-1">Pet photos uploaded during booking will appear here.</div>';return}state.galleryPhotos.forEach(src=>{const img=document.createElement("img");img.src=src;img.alt="Uploaded pet photo";els.photoGallery.appendChild(img)})}
function renderBookings(){if(!els.bookingList)return;els.bookingList.innerHTML="";state.bookings.forEach(b=>{const li=document.createElement("li");li.textContent=`${b.start} to ${b.end} — ${b.pet} (${b.name})`;els.bookingList.appendChild(li)})}
function renderBlocked(){if(!els.blockedList)return;els.blockedList.innerHTML="";blockedDates.forEach(date=>{const li=document.createElement("li");li.textContent=date;if(state.adminUser){const btn=document.createElement("button");btn.className="button ghost";btn.type="button";btn.style.marginLeft="8px";btn.style.padding="8px 12px";btn.style.fontSize=".85rem";btn.textContent="Remove";btn.addEventListener("click",()=>removeBlocked(date));li.appendChild(btn)}els.blockedList.appendChild(li)})}
async function removeBlocked(date){blockedDates=blockedDates.filter(d=>d!==date);await saveSettings();renderBlocked();renderStats();buildCalendar()}
window.addBlockedDate=async function(){if(!state.adminUser||!db)return;const input=document.getElementById("blockDate");if(!input||!input.value)return;if(!blockedDates.includes(input.value)){blockedDates.push(input.value);blockedDates.sort()}input.value="";await saveSettings();renderBlocked();renderStats();buildCalendar()}
async function saveSettings(){if(!db||!state.adminUser)return;await setDoc(doc(db,"site","config"),{blockedDates,maxPetsPerDay:Number(els.maxPets?.value||settings.maxPetsPerDay||3)},{merge:true});settings.maxPetsPerDay=Number(els.maxPets?.value||settings.maxPetsPerDay||3)}
window.saveMaxPets=async function(){if(!state.adminUser)return;await saveSettings();alert("Maximum pets per day saved.");renderStats();buildCalendar()}
function renderStats(){const c=counts(),vals=Object.values(c),busy=vals.length?Math.max(...vals):0;if(els.totalBookingsCount)els.totalBookingsCount.textContent=state.bookings.length;if(els.blockedDatesCount)els.blockedDatesCount.textContent=blockedDates.length;if(els.busiestDayCount)els.busiestDayCount.textContent=busy;if(els.dailyCountsList){els.dailyCountsList.innerHTML="";const entries=Object.entries(c).sort((a,b)=>a[0].localeCompare(b[0]));if(!entries.length)els.dailyCountsList.innerHTML='<div class="empty-state">No daily booking counts yet.</div>';else entries.forEach(([date,count])=>{const row=document.createElement("div");row.className="review-card";row.innerHTML=`<p><strong>${date}</strong></p><div class="review-meta"><span>${count} pet booking${count===1?"":"s"}</span><span class="stars">${"★".repeat(Math.min(count,5))}</span></div>`;els.dailyCountsList.appendChild(row)})}}
async function loadSettings(){if(!db)return;const snap=await getDoc(doc(db,"site","config"));if(snap.exists()){const data=snap.data();blockedDates=Array.isArray(data.blockedDates)?data.blockedDates:[];settings.maxPetsPerDay=Number(data.maxPetsPerDay||3)}else{blockedDates=[];settings.maxPetsPerDay=3}if(els.maxPets)els.maxPets.value=settings.maxPetsPerDay}
function adminVisible(user){state.adminUser=user||null;if(els.adminPanel)els.adminPanel.style.display=user?"block":"none"}
function subscribe(){if(!db)return;onSnapshot(doc(db,"site","config"),snap=>{const data=snap.exists()?snap.data():{};blockedDates=Array.isArray(data.blockedDates)?data.blockedDates:[];settings.maxPetsPerDay=Number(data.maxPetsPerDay||3);if(els.maxPets)els.maxPets.value=settings.maxPetsPerDay;renderBlocked();buildCalendar();renderStats()});onSnapshot(query(collection(db,"bookings"),orderBy("createdAt","desc")),snap=>{state.bookings=snap.docs.map(d=>({id:d.id,...d.data()}));state.galleryPhotos=state.bookings.map(b=>b.photoDataUrl).filter(Boolean);renderBookings();renderPhotos();renderStats();buildCalendar()});onSnapshot(query(collection(db,"reviews"),orderBy("createdAt","desc")),snap=>{state.reviews=snap.docs.map(d=>({id:d.id,...d.data()}));renderReviews()})}
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}))}
window.addEventListener("DOMContentLoaded",async()=>{cache();attachCalendar();ratingPicker();renderSelected();if(!configReady){showBanner("Firebase is not configured yet. Open firebase-config.js and paste in your Firebase web app config.");buildCalendar();renderReviews();renderPhotos();return}app=initializeApp(config);auth=getAuth(app);db=getFirestore(app);showBanner("Cloud storage is connected. Reviews, bookings and admin settings are stored in Firebase.");onAuthStateChanged(auth,u=>adminVisible(u));await loadSettings();subscribe();els.bookingForm?.addEventListener("submit",submitBooking);els.reviewForm?.addEventListener("submit",addReview);buildCalendar();renderReviews();renderPhotos()})
